server: helloServer.c
	gcc -Wall -Wextra helloServer.c -o helloServer

client: helloClient.c
	gcc -Wall -Wextra helloClient.c -o helloClient

clean: helloServer helloClient
	rm helloServer helloClient